---
- name: "Get AWS pass for docker"
  shell: aws ecr get-login-password --region eu-central-1
  register: aws_docker_registry_pass

- name: "Log root into AWS private registry"
  become: true
  community.docker.docker_login:
    registry_url: "{{ docker_mirror }}"
    username: AWS
    password: "{{ aws_docker_registry_pass.stdout }}"
    reauthorize: true

- name: "Log user into AWS private registry"
  become: true
  become_user: "{{ docker_user }}"
  community.docker.docker_login:
    registry_url: "{{ docker_mirror }}"
    username: AWS
    password: "{{ aws_docker_registry_pass.stdout }}"
    reauthorize: true