---
- name: Collect only facts returned by facter
  setup:
    gather_subset:
      - '!all'
      - '!any'

- name: 'Gather os specific variables'
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower | replace('/', '_') }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}-{{ ansible_architecture }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower | replace('/', '_') }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_architecture }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower | replace('/', '_') }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}-{{ ansible_architecture }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_architecture }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_system | lower }}-{{ ansible_architecture }}.yml"
        - "{{ ansible_system | lower }}.yml"
        - defaults.yml
      paths:
        - 'vars'

- name: 'pre-install docker'
  include_tasks: "pre-install/{{ ansible_system | lower }}.yml"

- name: 'install docker'
  include_tasks: "install/{{ ansible_system | lower }}.yml"
