---
- name: 'Get ec2 facts'
  amazon.aws.ec2_metadata_facts:

- name: 'Get vcpu count'
  ansible.builtin.shell: nproc
  register: vcpu_raw

- name: 'Set facts'
  set_fact:
    aws_s3_bucket: "{{ aws_bucket_na }}"
    vcpu_count: "{{ vcpu_raw.stdout | string }}"

- name: 'Set facts'
  when: ansible_ec2_placement_region == "ap-northeast-1"
  set_fact:
    aws_s3_bucket: "{{ aws_bucket_asia }}"

- name: 'Set facts'
  when: vcpu_config_map is defined and server_type == "gsm"
  set_fact:
    total_weight: "{{ vcpu_config_map.get(vcpu_count, vcpu_config_map.default).total_weight }}"
    compose_file: "{{ vcpu_config_map.get(vcpu_count, vcpu_config_map.default).compose_file }}"

- name: 'Setup node'
  when: server_type in ["be", "gsm", "simulator"]
  block:
    - name: 'Check params'
      ansible.builtin.assert:
        that:
# TODO: fix the check
#          - total_weight
          - versions_backend
          - versions_server
          - versions_gameparams
          - versions_deploy_scripts
          - prefix
          - db_prefix
          - kafka_prefix
          - wgn_api_key
        fail_msg: "parameters must be set"

    - name: "Ensure directories exist"
      ansible.builtin.file:
        path: /home/ec2-user/{{ item }}
        state: directory
        owner: ec2-user
        group: ec2-user
      loop:
        - "r3"
        - "r3/log"
        - "r3/.dynamic_configuration"

    - name: 'Ensure .env setup'
      ansible.builtin.template:
        src: "templates/.env.{{ server_type }}.j2"
        dest: /home/ec2-user/r3/.env
        owner: ec2-user
        group: ec2-user
        mode: 0644

    - name: 'Ensure setup.sh run'
      ansible.builtin.shell:
        cmd: ./setup.sh
        chdir: /home/ec2-user/r3
      tags:
        - never
        - setup

    - name: 'Write config.json'
      ansible.builtin.template:
        src: "templates/{{ versions_major }}/config.json.j2"
        dest: /home/ec2-user/r3/deploy_scripts/deploy_scripts_{{ versions_deploy_scripts }}/deploy_scripts/configs/config.json
        owner: ec2-user
        group: ec2-user
        mode: 0644

    - name: 'Write environment.json'
      ansible.builtin.template:
        src: "templates/{{ versions_major }}/environment-overrides.json.j2"
        dest: /home/ec2-user/r3/deploy_scripts/deploy_scripts_{{ versions_deploy_scripts }}/deploy_scripts/configs/environment-overrides.json
        owner: ec2-user
        group: ec2-user
        mode: 0644