apiVersion: v1
kind: Namespace
metadata:
  name: k8s-dev
  
---
apiVersion: v1
kind: ResourceQuota
metadata:
  namespace: k8s-dev
  name: dev-quota
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "2"
    limits.memory: "4Gi"
