apiVersion: v1
kind: Service
metadata:
  name: tracer-nodeport-service
spec:
  type: NodePort
  selector:
    app: tracer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1980 
      nodePort: 30050 
