---
- name: 'pre-install : manage docker user'
  when: false
  become: true
  block:
    - name: 'create docker group'
      group:
        name: '{{ docker_group }}'
        state: present
    - name: 'create docker user'
      user:
        name: '{{ docker_user }}'
        group: '{{ docker_group }}'
        create_home: false
        shell: '/bin/bash'
        state: present

- name: 'pre-install : Remove legacy docker repo file | Redhat'
  become: true
  when: ansible_distribution in ["CentOS","RedHat"]
  ansible.builtin.file:
    path: "{{ docker_repo_dir }}/docker.repo"
    state: absent
  changed_when: false

- name: 'pre-install : Ensure old versions of Docker are not installed | RedHat'
  become: true
  when:
    - ansible_os_family == 'RedHat'
    - (docker_versioned_pkg[docker_version | string] is search('docker-ce'))
  ansible.builtin.yum:
    name: '{{ docker_remove_packages }}'
    state: absent

- name: "setup : create needed folders"
  become: true
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - dest: "{{ docker_etc_dir }}"
      mode: 0711
    - dest: "{{ docker_daemon_graph }}"
