---
- hosts: all
  gather_facts: true
  roles:
    - role: software/docker_engine/docker_login
      tags: [ always ]

    - role: main/filebeat
      when: server_type in ["be", "gsm"]
      tags: [ always ]

    - role: main/setup_scripts
      tags: [ never,setup-scripts ]
    - role: main/update_params
      tags: [ always ]
