---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  yamllint molecule/shared/yaml-lint.yml

platforms:
  - name: java-amazonlinux-2023
    image: amazonlinux:2023
    privileged: true

provisioner:
  name: ansible
  log: true
  options:
    vvv: false
  config_options:
    defaults:
      force_color: true
  lint:
    name: ansible-lint
    options:
      force-color: true

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: testinfra
