---
ignore: |
  molecule/*/create.yml
  molecule/*/destroy.yml

extends: default

rules:
  line-length:
    max: 80
    level: warning
    allow-non-breakable-inline-mappings: true
  braces:
    level: warning
    max-spaces-inside: 1
  brackets:
    level: warning
    max-spaces-inside: 1
  colons:
    level: warning
  commas:
    max-spaces-before: 0
    max-spaces-after: 1
    level: warning
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    level: warning
  hyphens:
    level: warning
  indentation:
    level: warning
    indent-sequences: consistent
  truthy: disable
