---
- hosts: all
  gather_facts: true
  become: true
  vars:
    unmount_paths: []
  tasks:
    - name: 'Unmount path'
      ansible.posix.mount:
        path: "{{ item }}"
        state: unmounted
      loop: "{{ unmount_paths }}"
    - name: 'Absent path'
      ansible.posix.mount:
        path: "{{ item }}"
        state: absent
      loop: "{{ unmount_paths }}"
