#  mkdir -p /usr/local/lib/docker/cli-plugins
#  curl -SL https://github.com/docker/compose/releases/download/v2.28.0/docker-compose-linux-x86_64 -o /usr/local/lib/docker/cli-plugins/docker-compose
#  chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
#  curl -fL https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh | sh

---
- name: Install Pip
  dnf:
    name: python3-pip
    state: latest
  become: true

- name: Install Docker SDK for Python
  pip:
    name:
      - docker==5.0.3
    executable: pip3
    state: latest
  become: true

- name: Create Required Dirs
  ansible.builtin.file:
    name: /usr/local/lib/docker/cli-plugins
    state: "directory"
    recurse: true
    mode: "0755"
  become: true

- name: Download plugin
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
    dest: "/usr/local/lib/docker/cli-plugins/docker-compose"
    mode: '0755'
  become: true

- name: Verify Docker Compose installation
  command: docker compose version
  register: result
  failed_when: "'Docker Compose version {{ docker_compose_version }}' not in result.stdout"
