- name: Download Docker Compose Switch
  get_url:
    url: "https://github.com/docker/compose-switch/releases/download/{{ docker_compose_switch_version }}/docker-compose-linux-amd64"
    dest: /usr/local/bin/compose-switch
    mode: '0755'
  become: true

- name: "compose-switch : set alternatives"
  community.general.alternatives:
    name: docker-compose
    path: /usr/local/bin/compose-switch
    link: /usr/local/bin/docker-compose
    priority: 99
  become: true

- name: Verify Docker Compose Switch installation
  command: docker-compose version
  register: result_switch
  failed_when: "'Docker Compose version {{ docker_compose_version }}' not in result_switch.stdout"